### ISSUE TITLE
closeEvent doesn't seem to fire properly

### ISSUE THREAD

**Issue by rhytnen** [gmarull/qtmodern#8]
usage:
```
def main():
    app = QApplication(sys.argv)
    main_window = RemingtonUI()
    styles.dark(app)
    styled_window = windows.ModernWindow(main_window)
    styled_window.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
```

RemingtonUI usage:
```
class RemingtonUI(QMainWindow):
    def __init__(self):
        super(QMainWindow,self).__init__()
        # other setup here 
        self.ui = uic.loadUi('remington/resources/mainwindow.ui')
        self.setCentralWidget(self.ui)
```

The closeEvent call doesn't happen after clicking the red close button once  windows.ModernWindows(main_window) is called.  It doesn't happen if I set self.ui.closeEvent = self.closeEvent either.

**Comment by tisaconundrum2** [comment]
Perhaps, this is just the way the code got formatted here, but did you check to make sure your indentation is correct?

**Comment by rhytnen** [comment]
Yes, it's just a formatting mistake.   I'll fix it in the prior post.

My current work around for this is:
```
app.exec_()
main_window.closeEvent(None)
sys.exit()
```

**Comment by tisaconundrum2** [comment]
Can confirm that the bug is reproducible. 

Running the below code will return "It worked" (qtmodern is removed completely) 

```
class RemingtonUI(QMainWindow):
    def __init__(self):
        super(QMainWindow,self).__init__()
        # other setup here
        self.ui = uic.loadUi('MainWindow.ui')
        self.setCentralWidget(self.ui)

    def closeEvent(self, event):
        print("It worked")
        event.accept()

def main():
    app = QApplication(sys.argv)
    main_window = RemingtonUI()
    main_window.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
```

Whereas this code will not return anything at all.

```
class RemingtonUI(QMainWindow):
    def __init__(self):
        super(QMainWindow,self).__init__()
        # other setup here
        self.ui = uic.loadUi('MainWindow.ui')
        self.setCentralWidget(self.ui)

    def closeEvent(self, event):
        print("It worked")
        event.accept()

def main():
    app = QApplication(sys.argv)
    main_window = RemingtonUI()
    styles.dark(app)
    styled_window = windows.ModernWindow(main_window)
    styled_window.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
```

Interestingly, you can see that when evaluating `closeEvent` the methods are correctly bounded and are ready for use. 

![image](https://user-images.githubusercontent.com/11879769/31469064-3fbf368e-ae95-11e7-838d-4134b8691eea.png)


Edit: small note; inside `__init__`  I placed a `self.close()` after a `time.sleep()` and `closeEvent` does get called correctly with qtmodern. I'm definitely sure that something weird is going on

**Comment by tisaconundrum2** [comment]
Ok, I dug around, and I found where the problem is. `class ModernWindow(QWidget)` is subclassing `QWidget` and thus taking the `closeEvent` method. 

I added `closeEvent()` to `ModernWindow` and the closeEvent responded correctly with "It worked"

![image](https://user-images.githubusercontent.com/11879769/31469724-c257b420-ae97-11e7-9992-f304982a1e32.png)

**Comment by gmarull** [comment]
Hi,

One solution would be to subclass `ModernWindow` and _link_ there all the slots from the enclosed window. I have implemented the close event link on `ModernWindow`.
